site_name: Programming Practices for Research in Econonomics
pages:
- Getting Started: index.md
- Terminology: terminology.md
- Text Editor: textEditor.md
- Command Line Tools: commandLine.md
- Git: gitInstall.md
- Python: python.md
- R: r.md
# - Automation with Make: make.md
# - Automation with Waf: waf.md
# - Build Tools: snakemake.md
# - SQLite: sqlite.md
# - Matlab: matlab.md
# - Path Settings: path-setting.md
# - Contact: contact.md
# - Acknowledgements: acknowledgement.md

theme: readthedocs
